Making into disposition string to lowercase to fix the comparision issue
barbushin/php-imap pull request #566
Opened 2020-12-11 12:43 UTC by ambrous

Hi!

I faced an issue that in some cases field _disposition_ comes in upper case and due to that comparisions of `'attachment' == $partStructure->disposition` faild. It seems that it happens with outlook attachments.

Also, I'm not sure that is was a good idea to add an additional param to function of _downloadAttachment_, but I suppose it looks a bit more clear.

2021-02-23 15:12 UTC, Sebi94nbg commented
@ambrous this change seems to break something. Please rebase and solve this issue. Otherwise I'll close this pull request in the future.

2021-02-24 15:40 UTC, ambrous commented
@Sebi94nbg , I've rebased. However, I don't know how to recheck again by codeclimate.

2021-05-21 16:14 UTC, Sebi94nbg commented
@bapcltd-marv I'm kinda unsure about this change. Does it make sense to you? Would you merge it?

2021-09-09 17:08 UTC, ambrous commented
I think it is useful fix as sometime attachments are lost due to the low case of the disposition.

2022-12-05 15:42 UTC, Sebi94nbg requested changes
Sorry, forgot to publish my review. :disappointed:

2022-12-05 15:42 UTC, Sebbo94BY commented on src/PhpImap/Mailbox.php
> +    public function downloadAttachment(DataPartInfo $dataInfo, array $params, object $partStructure, bool $emlOrigin = false, bool $dispositionAttachment = false): IncomingMailAttachment
You are adding a new argument here and set it by default to `false`, but it seems like as it's never used, so it's always `false`. Isn't it?

2022-12-05 15:42 UTC, Sebbo94BY commented on src/PhpImap/Mailbox.php
> +        if ('RFC822' == $partStructure->subtype && isset($partStructure->disposition) && $dispositionAttachment) {
I'm still not sure, if this is a good replacement. I think, this will break (also) something.

Before: string comparisation
After: boolean comparisation

2022-12-14 09:40 UTC, ambrous commented on src/PhpImap/Mailbox.php
> +        if ('RFC822' == $partStructure->subtype && isset($partStructure->disposition) && $dispositionAttachment) {
This function skipped attachments in some emails due to case sensitive comparison.
I've just put almost the same comparison (but now it is not case sensitive) in one place and then use the boolean replacement of it, kind of some refactoring)

2022-12-14 09:40 UTC, ambrous commented on src/PhpImap/Mailbox.php
> +    public function downloadAttachment(DataPartInfo $dataInfo, array $params, object $partStructure, bool $emlOrigin = false, bool $dispositionAttachment = false): IncomingMailAttachment
No, please see the whole changed function not only my changes.

2026-05-10 13:39 UTC, closed without merging

2026-05-10 13:39 UTC, Sebbo94BY commented
Superseeded by https://github.com/barbushin/php-imap/pull/750. This issue should be solved now.