Adding support to keep original Filename of Attachment and open more flexibility
barbushin/php-imap pull request #645
Opened 2021-12-13 07:59 UTC by fglueck

can be extend with settings like "OVERWRITE_EXISTING _FILES" or like "GENERATE_FILENAME_IF_FILE_EXISTS"...

2021-12-13 22:25 UTC, Sebi94nbg commented
@fglueck can you please resolve the conflicts?

2021-12-27 23:17 UTC, Sebi94nbg commented
@fglueck friendly reminder :)

2022-01-10 10:52 UTC, Sebi94nbg commented
Can you please also squash your commits at the end, so that it's only one?

It would be also cool, when the commit message would be `Adding support for "original" Filename` instead of `Update Mailbox.php`.

Thank you! :)

2022-01-10 19:34 UTC, Sebi94nbg commented
I have unfortunately no permissions to change any settings of this project.

But you can usually rebase and squash locally and force push the changes, don't you?

Ok, if it's not possible, I also can squash and merge it through the buttons here. :)

2022-01-10 19:39 UTC, Sebi94nbg commented
Wouldn't it be a bit more beautiful and more human readable, when there would be some more underscores in the constant names? Like this?
```php
    public const ATTACH_FILE_NAME_RANDOM = 1; // Filename is unique (random)
    public const ATTACH_FILE_NAME_ORIGINAL = 2; // Filename is Attachment-Filename
    public const ATTACH_FILE_NAME_ITTERATED = 3; // Filename is Attachment-Filename but if allready exists it will be extend by Number (#nr)
```

2022-01-14 08:53 UTC, fglueck commented
Your right, I change the names and add itterated filename.

2022-01-14 16:19 UTC, Sebi94nbg commented
Perfect, I've already seen it.

There are some more reviews (see above). :)

2022-01-17 12:12 UTC, fglueck commented
You meen the "squash" ? I never do this before... so I can try to do this...

2022-01-17 12:22 UTC, Sebi94nbg commented
No, I mean these pending reviews in the code.

2022-12-05 15:43 UTC, Sebi94nbg requested changes
Sorry, forgot to publish my review. :disappointed:

2022-12-05 15:43 UTC, Sebbo94BY commented on src/PhpImap/Mailbox.php
> +    protected $attachmentsFilenameMode = self::ATTACH_FILE_NAMERANDOM;
```suggestion
    protected $attachmentsFilenameMode = self::ATTACH_FILE_NAMERANDOM;

```

2022-12-05 15:43 UTC, Sebbo94BY commented on src/PhpImap/Mailbox.php
> +    /** @var int */
```suggestion

    /** @var int */
```

2022-12-05 15:43 UTC, Sebbo94BY commented on src/PhpImap/Mailbox.php
> +     * @param int $random ATTACH_FILE_NAMERANDOM, ATTACH_FILE_NAMEORIGINAL
The variable in the comment should match the actual parameter variable.
```suggestion
     * @param int $mode ATTACH_FILE_NAMERANDOM, ATTACH_FILE_NAMEORIGINAL
```

2022-12-05 15:43 UTC, Sebbo94BY commented on src/PhpImap/Mailbox.php
> +        return $this;
Do we really need this return here? Wouldn't be a `void` function enough?

2022-12-05 15:43 UTC, Sebbo94BY commented on src/PhpImap/Mailbox.php
> +        $this->attachmentsFilenameMode = $mode;
I miss a check here, which ensures, that only supported modes can be set. Something like this:
```suggestion
        if (!defined($mode))
        {
                throw new UnexpectedValueException("The defined mode '$mode' is not supported. Supported modes: ATTACH_FILE_NAMERANDOM, ATTACH_FILE_NAMEORIGINAL");
        }

        $this->attachmentsFilenameMode = $mode;
```

Note: I haven't tested this code.

2026-05-10 14:05 UTC, Sebbo94BY commented
Thanks for your contribution!

I've rebased your changes based on the current code base.

This feature has been partitially already implemented as part of #751. The rest has been implemented as part of #751.

See the above linked pull requests for more details.

2026-05-10 14:05 UTC, closed without merging